language: rust

os:
  - linux
  - osx

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURE=accelerate
    - FEATURE=netlib
    - FEATURE=openblas
    - FEATURE=intel-mkl

matrix:
  exclude:
    - os: linux
      env: FEATURE=accelerate

before_install:
  - curl https://blas-lapack-rs.github.io/travis/fortran.sh | bash

script:
  - cargo test -vv --features=$FEATURE

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
