name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile=minimal --component clippy --component rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        feature:
          - accelerate
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile=minimal
      - run: cargo test --features=${{ matrix.feature }}
        env:
          FC: "$(brew --prefix gcc@13)/bin/gfortran-13"
          LIBRARY_PATH: "$(brew --prefix gcc@13)/lib/gcc/13"

  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile=minimal
      - run: cargo test --features=${{ matrix.feature }}
