name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - accelerate
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v3
      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --features=${{ matrix.feature }}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v3
      - name: Configure the environment
      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --features=${{ matrix.feature }}
