name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - openblas
    steps:
      - uses: actions/checkout@v3
      - name: Setup openblas
        run: |
          brew install openblas
      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --features=${{ matrix.feature }}
