name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - accelerate
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v3
      - run: brew install blis
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --features=${{ matrix.feature }}
        env:
          CC: gcc-13
          FC: gfortran-13
          LIBRARY_PATH: /usr/local/opt/gcc@13/lib/gcc/13

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          - blis
          - intel-mkl
          - netlib
          - openblas
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --features=${{ matrix.feature }}
